export enum ActionTypes {
	ALERT_BANNER_TEXT = 'ALERT_BANNER_TEXT',
	SWITCH_SCHOOL = 'SWITCH_SCHOOL',
	UPDATE_ONBOARDING_STAGE = 'UPDATE_ONBOARDING_STAGE'
}

export enum OnboardingState {
	CREATE_ADMIN = 'CREATE_ADMIN',
	CREATE_FACULTY = 'CREATE_FACULTY',
	CREATE_CLASS = 'CREATE_CLASS',
	ADD_STUDENTS = 'ADD_STUDENTS'
}