export enum ActionTypes {
	ALERT_BANNER_TEXT = 'ALERT_BANNER_TEXT',
	SWITCH_SCHOOL = 'SWITCH_SCHOOL',
	UPDATE_ONBOARDING_STAGE = 'UPDATE_ONBOARDING_STAGE'
}

export enum StaffType {
	TEACHING = 'TEACHING',
	NON_TEACHING = 'NON_TEACHING'
}

export enum OnboardingStage {
	ADD_STAFF = 'ADD_STAFF',
	ADD_CLASS = 'ADD_CLASS',
	ADD_STUDENTS = 'ADD_STUDENTS',
	COMPLETED = 'COMPLETED'
}

export enum MISFeePeriods {
	MONTHLY = 'MONTHLY',
	SINGLE = 'SINGLE'
}

export enum MISFeeLabels {
	SPECIAL_SCHOLARSHIP = 'SPECIAL_SCHOLARSHIP'
}
