export enum ActionTypes {
	ALERT_BANNER_TEXT = 'ALERT_BANNER_TEXT',
	SWITCH_SCHOOL = 'SWITCH_SCHOOL',
	UPDATE_ONBOARDING_STAGE = 'UPDATE_ONBOARDING_STAGE'
}

export enum OnboardingState {
	ADD_STAFF,
	ADD_CLASS,
	ADD_STUDENTS,
	COMPLETED
}