steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia.gcr.io/$PROJECT_ID/mischool-web:$SHORT_SHA', '--build-arg', 'VERSION=$SHORT_SHA', 'web']
  env:
    - 'VERSION=$SHORT_SHA'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/mischool-web:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/mischool-web-$BRANCH_NAME', 'mischool-web=asia.gcr.io/$PROJECT_ID/mischool-web:$SHORT_SHA']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=mischool-web-cluster'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://mischool-secrets/api-zone-slack-email', '/workspace/api-zone-slack-email']
- name: 'gcr.io/cloud-builders/curl'
  args:
  - '-X'
  - 'POST'
  - "https://api.cloudflare.come/client/v4/zones/$(cat api-zone-slack-email | awk '{print $2}')/purge_cache"
  - "-H"
  - "X-Auth-Email: $(cat api-zone-slack-email | awk '{print $4}')"
  - "-H"
  - "X-Auth-Key: $(cat api-zone-slack-email | awk '{print $1}')"
  - "-H"
  - "Content-Type: application/json"
  - "-d"
  - '{"purge_everything": true}'
- name: 'gcr.io/cloud-builders/curl'
  args:
  - '-X'
  - 'POST'
  - '--data-urlencode'
  - 'payload={\"channel\": \"#mis\", \"username\": \"Builder\", \"text\": \"MISchool has been successfully deployed from branch $BRANCH_NAME\", \"icon_emoji\": \":construction_worker:\"}'
  - "$(cat api-zone-slack-email | awk '{print $2}')"