steps:
  - name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/mischool-web:$SHORT_SHA']
  env:
    - 'VERSION=$SHORT_SHA'
  - name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/mischool-web:$SHORT_SHA']