steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'asia.gcr.io/$PROJECT_ID/mischool-web:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--cache-from'
  - 'asia.gcr.io/$PROJECT_ID/mischool-web:$BRANCH_NAME'
  - '-t'
  - 'asia.gcr.io/$PROJECT_ID/mischool-web:$SHORT_SHA'
  - '-t'
  - 'asia.gcr.io/$PROJECT_ID/mischool-web:$BRANCH_NAME'
  - '--build-arg'
  - 'VERSION=$SHORT_SHA'
  - 'web'
  env:
    - 'VERSION=$SHORT_SHA'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/mischool-web:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia.gcr.io/$PROJECT_ID/mischool-web:$BRANCH_NAME']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/mischool-web-$BRANCH_NAME', 'mischool-web=asia.gcr.io/$PROJECT_ID/mischool-web:$SHORT_SHA']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=asia-southeast1-c'
    - 'CLOUDSDK_CONTAINER_CLUSTER=mischool-web-cluster'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://mischool-secrets/api-zone-slack-email', '/workspace/api-zone-slack-email']
- name: 'gcr.io/cloud-builders/curl'
  entrypoint: 'bash'
  args: ['./web/scripts/clear-cloudflare-cache.sh']
- name: 'gcr.io/cloud-builders/curl'
  entrypoint: 'bash'
  args: ['./web/scripts/post-slack.sh', $BRANCH_NAME]